[workspace]
[package]
version = "0.1.0"
name = "invariant-proof-program"
edition = "2021"

[dependencies]
poly-invariant-proof = { path = "../invariant_proof" }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1", rev = "02c6ea6" }
